### ISSUE TITLE
When adding the library on Xcode 9 and Swift 4 I get the following error

### ISSUE THREAD

**Issue by rodydavis** [edwellbrook/Themeable#4] opened 2018-01-15 23:56 UTC
<img width="1175" alt="screen shot 2018-01-15 at 6 55 48 pm" src="https://user-images.githubusercontent.com/31253215/34965916-caf82946-fa25-11e7-9ce8-16284cff9845.png">

**Comment by edwellbrook** [comment] 2018-01-16 21:14
Hey @AppleEducate! Thanks for the heads up. This is caused by a change from swift 3 -> 4. I have a PR open to update to Swift 4 which should fix this. Will update you here once it's out.

**Comment by rodydavis** [comment] 2018-01-17 00:54
Awesome! I got it working temporarily until it's changed. Gotta say I love this library. Currently going through my app to set a pure plack them. Something I would suggest is to add a global current theme variable that wall all apply theme functions just call that variable and you can change the theme anywhere in the app. Currently doing this and works great.

Rody Davis - Content Creator
Rodydavis.com - Rody.davis.jr@gmail.com

**Comment by edwellbrook** [comment] 2018-01-18 23:33
Just merged in the Swift 4 updates and tagged as `v0.8.0`. Also updated on Cocoapods.

You can do what you just described by setting: `MyAppTheme.manager.activeTheme` where `MyAppTheme` is the name of your theme. See the example project for a working demo: https://github.com/edwellbrook/Themeable/blob/1039861c7cd57aba903946b2510ec400a4e95d4d/Example/ThemeableExample/ViewController.swift#L52-L56

Cheers!

**Closed as completed** 2018-01-18 23:33 UTC
